import { NextResponse } from "next/server"

export async function GET() {
  const cities = [
    "Colombo",
    "Kandy",
    "Galle",
    "Jaffna",
    "Negombo",
    "Anuradhapura",
    "Polonnaruwa",
    "Batticaloa",
    "Trincomalee",
    "Matara",
    "Ratnapura",
    "Badulla",
    "Kurunegala",
    "Puttalam",
    "Kalutara",
    "Gampaha",
    "Hambantota",
    "Vavuniya",
    "Chilaw",
    "Kegalle",
    "Nuwara Eliya",
    "Bandarawela",
    "Ella",
    "Sigiriya",
    "Dambulla",
    "Hikkaduwa",
    "Unawatuna",
    "Mirissa",
    "Bentota",
    "Beruwala",
    "Panadura",
    "Moratuwa",
    "Dehiwala-Mount Lavinia",
    "Sri Jayawardenepura Kotte",
    "Maharagama",
    "Kesbewa",
    "Kaduwela",
    "Kotikawatta",
    "Mulleriyawa",
    "Avissawella",
    "Homagama",
    "Padukka",
    "Hanwella",
    "Seethawaka",
    "Malabe",
    "Thalawathugoda",
    "Battaramulla",
    "Rajagiriya",
    "Nugegoda",
    "Kottawa",
  ]

  return NextResponse.json({ cities })
}
